trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - '*'

pr: none

pool:
  vmImage: 'ubuntu-24.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotnetSdkVersion: 8.0.x
  packageProject: '**/Angel.Social.Authentication.csproj'
  unitTestPathPattern: '**/*UnitTests/*.csproj'
  previewCounter: $[counter(variables['Build.SourceBranchName'], 1)]
  packagePreviewVersion: '$(Build.SourceBranchName)-preview$(previewCounter)'
  packageVersion: '$(Build.SourceBranchName)'

stages:
  - stage: Build_and_Test
    displayName: 'Build and Test'
    jobs:
      - job: Build
        displayName: 'Build and test'
        pool:
          vmImage: 'ubuntu-24.04'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK'
            inputs:
              version: '$(dotnetSdkVersion)'
              performMultiLevelLookup: true
          - task: DotNetCoreCLI@2
            displayName: 'Dotnet Restore'
            inputs:
              command: 'restore'
              projects: '$(solution)'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            displayName: 'Dotnet build $(buildConfiguration)'
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: 'Run unit tests'
            inputs:
              command: test
              projects: '$(unitTestPathPattern)'
              arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --collect:"XPlat Code Coverage"'
          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage report'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  - stage: NuGet_Pack_And_Push_Preview
    displayName: '(Preview) NuGet Pack and Push'
    dependsOn: Build_and_Test
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: 'Pack and Push to NuGet'
        pool:
          vmImage: 'ubuntu-24.04'
        environment: 'NuGetPreview'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: UseDotNet@2
                  displayName: 'Install .NET Core SDK'
                  inputs:
                    version: '$(dotnetSdkVersion)'
                    performMultiLevelLookup: true
                - task: DotNetCoreCLI@2
                  displayName: 'Pack NuGet Package'
                  inputs:
                    command: 'pack'
                    packagesToPack: '$(packageProject)'
                    versioningScheme: 'byEnvVar'
                    versionEnvVar: 'PACKAGE_VERSION'
                  env:
                    PACKAGE_VERSION: '$(packagePreviewVersion)'
                - script: |
                    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $(NuGetApiKey) --skip-duplicate
                  displayName: 'Push to NuGet.org'

  - stage: NuGet_Pack_And_Push_Official
    displayName: 'NuGet Pack and Push'
    dependsOn: Build_and_Test
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: 'Pack and Push to NuGet'
        pool:
          vmImage: 'ubuntu-24.04'
        environment: 'NuGetPush'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: UseDotNet@2
                  displayName: 'Install .NET Core SDK'
                  inputs:
                    version: '$(dotnetSdkVersion)'
                    performMultiLevelLookup: true
                - task: DotNetCoreCLI@2
                  displayName: 'Pack NuGet Package'
                  inputs:
                    command: 'pack'
                    packagesToPack: '$(packageProject)'
                    versioningScheme: 'byEnvVar'
                    versionEnvVar: 'PACKAGE_VERSION'
                  env:
                    PACKAGE_VERSION: '$(packageVersion)'
                - script: |
                    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $(NuGetApiKey) --skip-duplicate
                  displayName: 'Push to NuGet.org'
          